### ISSUE TITLE
Weird behavior on Kitty Terminal Emulator

### ISSUE THREAD

**Issue by uxdiin** [firecat53/bitwarden-menu#30] opened 2023-12-08 04:30 UTC
I am no sure if this is bwm issue or not, because it doesn't happened in other terminal emulator. The problem is the pasted text become lower case, and symbol turn into number ex: @ turn into 2, # turn into 3 and so on.

## Reproduce Step
1. Open Kitty Terminal
2. Call bwm and override autotype (in my case I use bwm -a {PASSWORD})
3. Select Any of your cred that has uppercase letter or symbol
3. You will see it all turn into lowercase and the symbol turn into number

**Comment by uxdiin** [comment] 2023-12-20 00:26
I am also on nixos, and I installed the package from nixpkgs unstable, I have tried to use kitty without any config, and the problem still exits. I am using bspwm and i have tried the type library like you said, but it behave normally. I will come back later when I found the culpirt, thanks for the response.

**Comment by uxdiin** [comment] 2024-02-09 13:58
I still haven't found the culprit yet, but this weird behavior is now happens on latest version of alacrity as well, don't know if that's bring some clue or not.

**Comment by firecat53** [comment] 2024-03-15 17:11
Any other information on this? I use alacritty with ydotool daily and haven't seen this.

I have noticed on NixOS that when I switch between X and Wayland without a reboot that pynput will not work correctly on X. But I have no troubles on Wayland with ydotool or wtype.

**Comment by firecat53** [comment] 2024-03-27 03:32
Any other info? I'm still unable to reproduce on Alacritty or Kitty (NixOS unstable).

**Comment by firecat53** [comment] 2024-05-02 15:45
Closing. If you have additional information please reopen. Thanks!

**Closed** 2024-05-02 15:46 UTC
